version: '3.1'

services:
  web:
    image: nginx:1.20.1m
    build:
      context: ./
      dockerfile: Dockerfile-nginx
      args:
        container_name: nginx:1.20.1m
    volumes:
      - nginx_conf:/etc/nginx
    ports:
      - "80:80"
    depends_on:
      - go-contacts

  go-contacts:
    image: gocontacts:1.0
    restart: always
    build:
      context: ./
      args:
        container_name: gocontacts:1.0
    environment:
      - db_name=gocontacts
      - db_pass=
      - db_user=postgres
      - db_host=pg_db
      - db_port=5432
    depends_on:
      - pg_db
      
  pg_db:
    image: postgres:13.4m
    build:
      context: ./
      dockerfile: Dockerfile-postgres
      args:
        container_name: postgres:13.4m
    restart: always
    environment:
      - POSTGRES_PASSWORD=
      - POSTGRES_USER=postgres
      - POSTGRES_DB=gocontacts
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - db_data:/var/lib/postgresql/data
#    ports:
#      - ${POSTGRES_PORT:-5432}:5432

volumes:
  db_data:
  nginx_conf:

